language: android
jdk: oraclejdk8
android:
        components:
                - platform-tools
                - build-tools-25.0.2
                - android-25
                - extra-android-m2repository
        licenses:
            - android-sdk-license-.+
            - '.+'
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew

branches:
        only:
                - master